#4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.

In [ ]:
import numpy as np
arr1=np.array((2,2))
print(arr1)

[2 2]


#2. Initialize an all one array with size 4X2.

In [ ]:
import numpy as np
arr2=np.ones((4,2))
print(arr2)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


#3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
import numpy as np
arr3=np.full((2,2),1)
print(arr3)

[[1 1]
 [1 1]]


#4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
import numpy as np
arr4=np.array([[1,2],[3,4]])
arr_zero=np.zeros_like(arr4)
print(arr_zero)

[[0 0]
 [0 0]]


#5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
import numpy as np
arr5=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_one=np.ones_like(arr5)
print(arr_one)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


#6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np
new_list=[1,2,3,4]
arr6=np.array(new_list)
print(arr6)

[1 2 3 4]


#Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.


In [ ]:
import numpy as np
arr7=np.arange(10,49)
print(arr7)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [ ]:
import numpy as np
arr8=np.arange(0,9)
reshape_array=np.reshape(arr8,(3,3))
print(reshape_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
import numpy as np
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [ ]:
import numpy as np
arr1=np.random.random(30)
mean=arr1.mean()
print(arr1)
print(mean)

[0.25102034 0.10398701 0.18093541 0.59590389 0.95972062 0.98011777
 0.37880345 0.87664942 0.06419879 0.01981927 0.9225422  0.4467926
 0.81916176 0.73456583 0.03993768 0.4745804  0.24987974 0.06264229
 0.95629158 0.73468985 0.59832332 0.46716075 0.82898648 0.44048719
 0.50305993 0.01500969 0.82030885 0.59939884 0.52839941 0.12380142]


#5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
import numpy as np
arr1=np.random.random((10,10))
mini=np.min(arr1)
maxi=np.max(arr1)
print(arr1)
print(mini)
print(maxi)

[[0.56289008 0.36029288 0.32530477 0.25951801 0.13141469 0.34685336
  0.79638991 0.39865589 0.55420426 0.86961632]
 [0.21077369 0.76972105 0.81718928 0.10777219 0.64930933 0.93327761
  0.64529598 0.38958167 0.87302583 0.9028533 ]
 [0.46165317 0.18590343 0.50215917 0.01036361 0.32622823 0.92934083
  0.52976462 0.86114144 0.7687343  0.60647602]
 [0.7449702  0.3666194  0.99881139 0.84004657 0.13988152 0.05538193
  0.83175235 0.25092354 0.98838782 0.22964376]
 [0.48507066 0.80419305 0.56272521 0.23060426 0.45150564 0.01176742
  0.89188897 0.82417183 0.44240491 0.95410079]
 [0.74701944 0.45928667 0.47632444 0.22373884 0.06577597 0.58492116
  0.22198491 0.12533453 0.77692105 0.21600697]
 [0.58765495 0.3368233  0.94424674 0.25183903 0.12305939 0.00134003
  0.49155747 0.00407047 0.86075754 0.90508193]
 [0.97796773 0.31205223 0.99110741 0.02516036 0.07300432 0.99000503
  0.64436644 0.9599048  0.90596748 0.91971443]
 [0.19934201 0.19930766 0.05192491 0.95689886 0.84377819 0.10363225
  0.71004442

#6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
import numpy as np
arr1=np.zeros((4,6))
arr1[:, 4] = 1
print(arr1)

[[0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]]


#7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
import numpy as np
arr = np.array([1, 2, 0, 0, 4, 0])
print(arr[::-1])

[0 4 0 0 2 1]


#8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
import numpy as np
arr=np.ones((4,4))
arr[1:-1,1:-1]=0
print (arr)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np
arr=np.ones((8,8))
arr[1::2, ::2]=0
arr[::2, 1::2]=0
print (arr)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.

In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
addition1=np.add(x,y)
addition2=np.add(v,w)
print("Addition of x and y=",addition1)
print("Addition of v and w=",addition1)

Addition of x and y= [[ 6  8]
 [10 13]]
Addition of v and w= [[ 6  8]
 [10 13]]


#2. Subtract the two array.

In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
subtract1=np.subtract(x,y)
subtract2=np.subtract(v,w)
print("Subtract of x and y=",subtract1)
print("Subtract of v and w=",subtract2)

Subtract of x and y= [[-4 -4]
 [-4 -3]]
Subtract of v and w= [-2 -2]


#3. Multiply the array with any integers of your choice.

In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
v = np.array([9,10])
multiply1=np.multiply(x,2)
multiply2=np.multiply(v,3)
print("Multiplying x with 2=",multiply1)
print("Multiplying v with 3=", multiply2)

Multiplying x with 2= [[ 2  4]
 [ 6 10]]
Multiplying v with 3= [27 30]


#4. Find the square of each element of the array.

In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
square1=np.square(x)
square2=np.square(y)
square3=np.square(v)
square4=np.square(w)
print("Square of x=",square1)
print("Square of y=",square2)
print("Square of v=",square3)
print("Square of w=",square4)

Square of x= [[ 1  4]
 [ 9 25]]
Square of y= [[25 36]
 [49 64]]
Square of v= [ 81 100]
Square of w= [121 144]


#5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
Product1=np.dot(v,w)
Product2=np.dot(x,v)
Product3=np.dot(x,y)
print("Dot product of v and w=",Product1)
print("Dot product of x and v=",Product2)
print("Dot product of x and y=",Product3)

Dot product of v and w= 219
Dot product of x and v= [29 77]
Dot product of x and y= [[19 22]
 [50 58]]


#6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
hstacked=np.hstack((x,y))
vstacked=np.vstack((v,w))
print("Concatenate along row=",hstacked)
print("Concatenate along row=",vstacked)

Concatenate along row= [[1 2 5 6]
 [3 5 7 8]]
Concatenate along row= [[ 9 10]
 [11 12]]


#7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
v = np.array([9,10])
concate_xaxis=np.concatenate((x,v),axis=0)
print(concate_xaxis)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Due to their shape mismatch it caused error.

#Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)T = BTAT

In [ ]:
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

Inverse_of_A=np.linalg.inv(A)
Identity=np.dot(A,Inverse_of_A)
print(Identity)
print("\n")
AB=np.dot(A,B)
BA=np.dot(B,A)
print("A * B =", AB)
print("B * A =", BA)
print("\n")
transpose_AB=np.transpose(AB)
transpose_A=np.transpose(A)
transpose_B=np.transpose(B)
A_transpose_B_transpose=np.dot(transpose_B,transpose_A)
print("Transpose of AB=",transpose_AB)
print("Transpose of A and B=",A_transpose_B_transpose)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


A * B = [[23 13]
 [51 29]]
B * A = [[36 44]
 [13 16]]


Transpose of AB= [[23 51]
 [13 29]]
Transpose of A and B= [[23 51]
 [13 29]]


#• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [ ]:
import numpy as np
A=np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
B=np.array([-1,-3,9])
A_Inverse=np.linalg.inv(A)
X=np.dot(A_Inverse,B)
print(X)
print("\n")
X2=np.linalg.solve(A,B)
print(X2)

[ 2.  1. -2.]


[ 2.  1. -2.]
